import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getPokemon, getPokemonImg, getPokemonInterval } from "./api/endpoints";
import styles from "../styles/home.module.css";

const Home: NextPage = () => {
  let [spriteImg, setSpriteImg] = useState("");
  let [pokemonList, setPokemonList] = useState([]);
  let [checkOpen, setCheckOpen] = useState<boolean>(false);
  let [valueInput, setValueInput] = useState<string>("");

  function getListFiltered(pokemonListProps: any) {
    let auxPokemonList = pokemonListProps.filter((value: any) => {
      return value.name.toLowerCase().indexOf(valueInput.toLowerCase()) > -1;
      // Quando o indexOf não acha resultados, ele retorna o index -1
    });

    return auxPokemonList;
  }

  useEffect(() => {
    getPokemonInterval(0, 1154, setPokemonList);
  }, []);

  function onChangeInput({ target }: any) {
    setValueInput(target.value);
  }

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title">Pokedex</h1>
      <div className="centerAligned">
        <input
          placeholder="Insira o nome do Pokemon"
          className={styles.inputPesquisa}
          value={valueInput}
          onChange={(e) => {
            onChangeInput(e);
          }}
        />
        <p>{valueInput}</p>
      </div>
      <div className={styles.buttonList}>
        {checkOpen ? (
          <div className={styles.centerImg}>
            <img src={spriteImg} className={styles.bigImage} width="200" />
            <button
              onClick={() => {
                setCheckOpen(false);
              }}
            >
              Voltar
            </button>
          </div>
        ) : (
          getListFiltered(pokemonList).map((pokemon: any) => {
            return (
              <button
                key={pokemon.name}
                className={styles.button}
                onClick={() => {
                  getPokemonImg(pokemon.name, setSpriteImg);
                  setCheckOpen(true);
                }}
              >
                {pokemon.name}
              </button>
            );
          })
        )}
      </div>
    </div>
  );
};

export default Home;
